# Generated by Django 2.2.3 on 2019-07-03 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='ficheros')),
            ],
        ),
    ]
