# Generated by Django 2.2.3 on 2019-07-03 21:33

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='my_json_field',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
